### PR TITLE
use api token for remaining calls.

### LINKED ISSUE #10: Authenticated requests
Note that the rate limits can be exceeded. As such, perhaps it would be possible to allow configuring an API key for authenticated requests.

### PR DESCRIPTION
**Pull request by paulirish**
fixes #10

### CODE REVIEW

**Comment by paulirish** [comment]
@DaveJarvis this make sense to you?

if the env var isn't set, it's an empty string, which is handled just fine by the API.

**Comment by ghost** [comment]
See PR #13 as there is already a de facto `GITHUB_TOKEN` environment variable.

My preference would be to have the script persist the token in a hidden file in the user's home directory if the `GITHUB_TOKEN` environment variable isn't found (as per PR #13). This saves users from having to edit their `.bashrc` altogether.

**Comment by JagOffical** [comment]
Hey question for you guys, how do you use this?

**Comment by ghost** [comment]
@JagOffical See https://github.com/DaveJarvis/github-email until @paulirish merges the changes. Basically, the usage is:

``` bash
git clone https://github.com/DaveJarvis/github-email
cd github-email
./github-email.sh paulirish
```

The script will tell you what requirements are needed to make it work.

**Comment by paulirish** [comment]
updated along with the auth header fix for #23

**Pull request merged**
